### ISSUE TITLE
Error when using example code

### ISSUE THREAD

**Issue by anderhil** [DmytryS/uz-booking-api#3]
Hello, 

I have an issue when trying your example code from README. 

I receive this
![2021-02-15 17_57_50-](https://user-images.githubusercontent.com/2346562/107982302-11edc380-6fc4-11eb-9bfa-175d491f009a.png)

when doing `.Train.find` although the `.Station.find` call works OK.

Do you know why this happens?

**Comment by DmytryS** [comment]
UZ disabled their mobile api, that's why some endpoints doesn't work...

**Comment by DmytryS** [comment]
library updated to use new mobile app api

**Comment by anderhil** [comment]
Hi, thanks, thats true, it was working some time after your update. However currently sendsms and login work, but for some reason after calling any other apis the response is 
```
{
    "message": "Тимчасовий збій. Увійдіть в акаунт наново."
}
```

It has been like this for couple of months already. Do you know why this started happening?
